### ISSUE TITLE
Duplicate ports in firewall config?

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-appliance-build#108]
https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/firewalld.ks.erb

@carbonin @abellotti Do we need ssh, http, https, postgres listed multiple times in the firewall config?

**Comment by abellotti** [comment]
by name vs. by number, probably not.  personally, I'm more partial to the by number, but that's just me. Thanks.
