### ISSUE TITLE
Support bower in manageiq

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-appliance-build#117]
After https://github.com/ManageIQ/manageiq/pull/7577, we'll need to have `bower` available in the appliance for ManageIQ (previously, it was only needed for SSUI).

Not quite sure what's needed here if anything, possibly https://github.com/ManageIQ/manageiq-appliance/pull/65 handles it .. but not sure, can anyone look at it please?

**Comment by Fryguy** [comment]
The only thing I can see is that maybe this comment should be changed: https://github.com/ManageIQ/manageiq-appliance-build/blob/ffe799032a1a2ab40ead63f4a6d3bcdba7e4209f/kickstarts/partials/packages/includes.ks.erb#L84-L85

**Comment by himdel** [comment]
Right.. https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/bundler.ks.erb made me think that since we're doing something bundler-related, we may need to handle this as well, but.. should I do a PR for the comment thing?

**Comment by Fryguy** [comment]
might as well...it's pretty small :)

**Comment by Fryguy** [comment]
I think the changes to cfme-setup.sh in ManageIQ/manageiq-appliance#65 *should* handle it.

**Comment by himdel** [comment]
Aand here it is.. https://github.com/ManageIQ/manageiq-appliance-build/pull/118
