### ISSUE TITLE
Do not continue creating image when commands in %post section (e.g. bundle install) fails

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#127]
Currently, we don't catch any error coming from commands ran in %post section of kickstart.  Some errors are fatal and appliance won't work at all, but we continue creating images anyway.

Would be nice to grab the anaconda-post.log, then stop the process, to avoid generating images that won't work.

**Comment by mfeifer** [comment]
@simaishi what would you like to do with this old issue?

**Comment by simaishi** [comment]
I've pinned the issue and assigned to myself. I'm still trying to figure out if this can be done, as this is really helpful if it can be done.

**Comment by simaishi** [comment]
With rpm based appliance, we no longer need to get this done. What sometimes failed in the %post section is now all done during rpm build.
