### ISSUE TITLE
Cloud-init not needed on most platforms

### ISSUE THREAD

**Issue by geertj** [ManageIQ/manageiq-appliance-build#147]
From [`kickstarts/partials/packages/includes.ks.erb`](https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/packages/includes.ks.erb#L82):

``` erb
<% if @target != "azure" && @target != "gce" %>
cloud-init
<% end %>
```

However there are other platforms that should be excluded. In fact, only the following platforms support cloud-init
- openstack
- ovirt

All other platforms do not support it. (Note that EC2 does supports cloud-init as well but we're not building for EC2 yet).

I would suggest we invert the logic and only include cloud-init on the platforms mentioned above. The benefit is slightly less space, slightly faster booting and no ugly cloud-init messages on the console.

**Comment by carbonin** [comment]
I think [vSphere](https://cloudinit.readthedocs.io/en/latest/topics/datasources.html#vsphere) technically supports it also, but I was never able to get it to work.

@jvlcek Can you add anything here about which platforms you were able to get working with cloud-init?

**Comment by jvlcek** [comment]
@geertj In the past openstack, ovirt and vsphere had support for cloud-init.

Of the 6 images we currently build that leaves:
azure, hyperv and vagrant, of which we already excluded cloud-init in azure.

I'm not sure if it makes sense to not build cloud-init into these images or
if we should work on supporting cloud-init in as many images as feasible.

**Comment by geertj** [comment]
> I'm not sure if it makes sense to not build cloud-init into these images or
if we should work on supporting cloud-init in as many images as feasible.

Yeah, that's a great question. I went back and forth a couple of times on this. A few years back it looked like cloud-init was going to be the standard for configuring cloud images. That hasn't materialized. The original cloud-init code is extremely ugly. This lead both OpenStack, CoreOS and CloudBase to develop their own variant of it. And then people started introducing guest agents: the Azure agent, Google agent, QEmu guest agent, oVirt guest agent (and of course the venerable VMware tools). All of these can deploy ssh keys and run commands which is really the only thing that's required here.

vsphere by the way doesn't really support cloud-init other than the ability to attach a custom CD-ROM that you need to build yourself with mkisofs. Both oVirt and OpenStack have "native" support where you just input the user-data file, and they build the image for you and attach it.

**Comment by jvlcek** [comment]
@geertj, Well if cloud-init is no longer the mechanism of choice and is not going to be, I'd agree that delivering it is probably not important.

**Comment by karmab** [comment]
i believe cloudinit is still widely used.
straight kvm can be used for testing the appliance and keeping cloudinit there would not only help setting network configuration but also preconfigure the appliance using runcmds

**Comment by geertj** [comment]
@karmab can you elaborate? Are you saying you run appliances other than the oVirt and OpenStack appliances with KVM (not oVirt). So how do you do this? Do you mkisofs a CD and put the multi-part MIME file on it? And what is the use case for doing this?

**Comment by karmab** [comment]
I exactly do that, running manageiq or cloudforms on straight kvm and
trying to have it configured with cloudinit.

I use a tool i develloped to make all the process easy:
you can see the cloudinit script im trying to use at
https://github.com/karmab/kcli/tree/master/uci/manageiq

The use case is to quickly launch either a single appliance or a more
advanced stack with also ovirt, openstack,... for testing and showcase and
with the only requirement of kvm libvirt (either locally or remotely)
