### ISSUE TITLE
Disable ssh password logins

### ISSUE THREAD

**Issue by geertj** [ManageIQ/manageiq-appliance-build#148]
Currently both [azure](https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/azure.ks.erb#L8) and [gce](https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/gce.ks.erb#L4) disable password logins in `/etc/ssh/sshd_config`.

Because we have a non-private root password in our appliance, we should really disable network password logons for all platform for obvious security reasons. Note that all our supported platforms have an alternate, secure way of logging into the system:
- Have an agent that allows deploying ssh keys: gce, azure
- Use cloud-init to deploy ssh keys: openstack, ovirt
- Login via standard username/password on not network accessible console: vsphere, ovirt, hyperv, libvirt, vagrant.

**Comment by Fryguy** [comment]
@carbonin Thoughts?

**Comment by abellotti** [comment]
I recall some folks at the design summit asking to be able to ssh to the appliance using their IPA credentials once ext auth is enabled. I wonder if this should be optional.

**Comment by carbonin** [comment]
I think this would be a bit disruptive for installations that are deploying more than a few appliances at a time.

Also I'm not sure if we do this for other things as well, but I know that we rely on scp to retrieve the `v2_key` for environments with multiple appliances. So that, at least, would be broken on first setup.

Maybe something in between would be a better step? Maybe remove ssh for the root user and create a separate user that is usable with ssh but not allowed to `sudo`? Or maybe just make a console option to change the root user password and strongly recommend that is done (MOTD)?

I'm not sure what kind of things people are doing with ssh in the field though. For example if people are using ansible to deploy/configure our appliances (@akrzos), they would likely be quite disrupted by this change. I understand the concern, but we would need to look at this quite a bit more before making this change.

**Comment by geertj** [comment]
Coming back to this after a some more thinking on this. I think the following two statements are correct:

1. Having a user (especially root) with a default password that can login via the network with that password is a real security issue. Many first time users will not know about this, making them vulnerable as they will leave the root password unchanged. And even for more experienced users, there is a window of time, just after deploying a new appliance, and before they change the password, where that appliance is vulnerable. 

2. Console logins with a default password are fine and actually desirable. Physical (virtual) access to a console usually means you can control the box anyway, and all hypervisors that I know of consider console access a privileged operation. Console access is super useful to diagnose issues. And it's useful even in situations where is no console access (e.g. in Amazon). When you're troubleshooting an issue with an Amazon appliance, you can run it locally, and log on via the console.

Now @carbonin brings up a good point: what about the v2_key transfer. I had a quick look and I understand that the appliance_console has a menu to transfer a key via ssh username/password. So we need to find a solution to this, but ideally while still having 1. and 2. above.

What about the following:

* Disable ssh logins for root when using a password. This can be achieved with `PermitRootLogin prohibit-password`, which is actually the default in newer ssh version (post CentOS-7). Since root is the only user with a default password, this removes any network logins via a default password, but it still allows console logins which as mentioned above super useful for debugging.

* Add a new option to the appliance console called "Temporarily enable key transfers". This will enable a local account (not root) with a random password. It will show the host name, username and password on the screen. Using this data, you can transfer the key from the other appliance. Once you press ENTER on the first appliance, the screen is cleared, the account locked again, and you go back to the main menu.

The key transfer mechanism is similar to how many other security protocols work, e.g. bluetooth pairing where you temporarily allow access via a random code.

Ansible uses public keys for root by default, so this will still work. Theoretically Ansible can use passwords but the docs strongly discourage it and nobody that I know uses it in that way.

I did some grepping in the source and the only other place that I can see that uses scp is in the OpenShift installer state machine. But it doesn't scp to the appliance.

We would enforce this standard configuration for all targets.

**Comment by mfeifer** [comment]
cc @simaishi
