### ISSUE TITLE
Change and test symlinking code to not change directories

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-appliance-build#15]
See: https://github.com/ManageIQ/manageiq-appliance-build/pull/14#discussion_r34285335

It's not a difficult change, but requires some testing... putting this here to remember to do it.

**Comment by kbrock** [comment]
heh. now that appliance_console is merged, we'll see how this all comes together tomorrow

**Comment by Fryguy** [comment]
Yeah, chdir is not necessary.  ln doesn't resolve the first parameter...it just uses it directly.
