### ISSUE TITLE
Upload Vagrant boxes to Atlas

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-appliance-build#151]
Now that #144 has been merged and we build Vagrant boxes, we should upload them to Atlas.

I started this effort, but I can't figure it out completely, so I'm punting over to @geertj .

The things we will need are probably:
- Uploads of the nightly builds on master
- Uploads of the release versions

For the nightly builds, I created a box at https://atlas.hashicorp.com/ManageIQ/boxes/manageiq/versions/5.0.0-pre .  Note that Atlas _requires_ a numerical version, so given that Euwe is the 5th letter of the alphabet, and master is the nightly version of that, I chose `5.0.0-pre`.  I would expect the darga-1 release to be `4.1.0`, darga-2 to be `4.2.0`, etc.

So, I created a box, but now I have no idea what to do with it.  Apparently I have to create a "provider" underneath it and maybe choose "virtualbox"?  I'm not really sure.  Then I'm not sure how to upload...I found atlas-upload-cli, but i don't know if that works.

So, @geertj , can you investigate?

**Comment by geertj** [comment]
I'm on it! See my recent PR to imagefactory, which got merged today :)

https://github.com/redhat-imaging/imagefactory/pull/382

What remains to do is to call the automation from vmbuild.rb. My suggestion would be to only upload releases to Atlas (and GCE, and other clouds we want to support), and keep the nightlies only on releases.manageiq.org.

**Comment by simaishi** [comment]
I looked into this before. Tried to use the imagefactory plugin, but the upload kept failing (it will start, but times out), and I was never able to upload an image using the plugin. Will try again when we have a new build machine.

Note, this will also require a small change to imagefactory plugin so it uploads without releasing the image.

**Comment by simaishi** [comment]
@Fryguy We currently create vagrant box pointing to image at releases.manageiq.org (rather than uploading the image to vagrant cloud). Is that how we'll continue creating the boxes going forward?

**Comment by Fryguy** [comment]
I think as long as vagrant cloud shows the user how to get the image, it doesn't matter where it lives.  I can see them there now at https://app.vagrantup.com/manageiq/ , so I think this is sufficient.  Maybe we could open a separate issue for automating the listing on vagrant cloud, but otherwise this issue is "done", IMO.

**Comment by simaishi** [comment]
> automating the listing on vagrant cloud

We're on the same page, that's what I was planning to do (after running into issue trying to upload...) 😄
