### ISSUE TITLE
Cleanup how to add target specific partials for kickstart

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#152]
Adding partials for specific target can be cleaned up, see https://github.com/ManageIQ/manageiq-appliance-build/pull/150#discussion_r75921955

Also blank lines added for each tag in output can be removed by adding trim mode for better readability.

**Comment by mfeifer** [comment]
@simaishi is this still needed?

**Comment by mfeifer** [comment]
@simaishi does this issue still need to stay open?

**Comment by simaishi** [comment]
We have to keep a list of target that has target specific erb (so it will fail if file is missing), so it's probably best to keep this as is.
