### ISSUE TITLE
Doc build failing with ascii_binder v0.1.5

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#166]
docbuild has been failing since ascii_binder v0.1.5 came out.

```
bundler: failed to load command: ascii_binder (/opt/rubies/ruby-2.2.5/bin/ascii_binder)
LoadError: cannot load such file -- /opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/specifications/bin/ascii_binder
  /opt/rubies/ruby-2.2.5/bin/ascii_binder:23:in `load'
  /opt/rubies/ruby-2.2.5/bin/ascii_binder:23:in `<top (required)>’
```

**Comment by Fryguy** [comment]
I saw that issue locally and I just can't understand it :(  Our manageiq_docs builds are failing for the same reason.  cc @nhr

**Comment by abellotti** [comment]
check the change @jvlcek needed to do in his PR: https://github.com/ManageIQ/manageiq_docs/pull/139/files

changing bundle exec ascii_binder to bundle exec asciibinder in the Rakefile

**Comment by nhr** [comment]
See this AsciiBinder issue: https://github.com/redhataccess/ascii_binder/issues/64
Is it possible that under Ruby 2.3.1 that the gemspec line referenced there is not picking up the symlink? The odd part is that `ascii_binder` is the actual file and `asciibinder` is the symlink to same...

**Comment by nhr** [comment]
Oh, I take it back - `asciibinder` is the actual file. So I bet that we need to fix the gemspec.
