### ISSUE TITLE
Default root login and password on GCE manageiq appliance/image

### ISSUE THREAD

**Issue by Rambo68** [ManageIQ/manageiq-appliance-build#197]
Hi:

Is there anyway to access the console from GCE? I Keep getting permission denied. I've tried admin/password admin/smartvm root/password root/smartvm. 

Thanks, 

Angel

**Comment by simaishi** [comment]
@Rambo68 For GCE, 'root' account is locked and the only way to access console is to set up SSH key for the instance (https://github.com/ManageIQ/manageiq-appliance-build/pull/136).

**Comment by Rambo68** [comment]
I see that. However, would you know how it is done in GCE?

**Comment by simaishi** [comment]
I assume you're asking where to set up SSH key?  When you create an instance, click "Management, disk, networking, SSH keys" -> "SSH Keys".  You can set up project-wide or instance specific SSH key there.

**Comment by Rambo68** [comment]
Yes, I will try again as I have already tried this and it didn’t work.

**Comment by Rambo68** [comment]
Is there another user I can access from the serial console? The ssh does not seem to be working. I have multiple instances and K8 Clusters I can ssh to just fine. 

 

Thanks, 


Angel

**Comment by Rambo68** [comment]
Hi:


I wanted to give you an update on your GCE image. I don’t think you have the google cloud tools installed which makes it impossible to login to the console. You can’t SSH into it from gcloud, or from the cloudshell because the GCE tools are not installed. Also, you have the root account locked and no other reference account is listed to permit login. The only account you have listed is admin/smartvm as you know root is locked. I deployed it manually by building an instance and using Ansible to deploy it. All worked fine. Thanks for your assistance. 

 

Cheers, 


Angel

**Comment by simaishi** [comment]
I'm sorry I forgot to update this issue... I tried euwe-2 appliance and confirmed no SSH access.  The kickstart log showed the google compute engine packages are installed, but the console log didn't show setting up instance, which explains why SSH isn't working.

I'll dig into this more. Thank you for reporting the issue.

**Comment by Rambo68** [comment]
Thanks my friend. I love the product!

**Comment by savillep** [comment]
Hi, I think the latest Oparin-1 release has this issue.  Viewing the console logs of machine built using the gce image and can't see the google tools being deployed.  Can't access the VM via SSH.  Using the older Fine-4 image works as expected. Console logs confirm the difference.
I'm just setting up to test and learn and am totally new to the product.
