### ISSUE TITLE
Get rid of floppy not found kernel/syslog message in appliance image

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-appliance-build#198]
Existing centos 7.3 vmware MIQ appliance keep logging floppy not found message from dmesg and syslog message.

This can be resolved by booting VM into bios mode and disable the floppy controller.
Not sure if you can disable it inside *.vmx file

Let me know if you need more detail

https://github.com/ManageIQ/manageiq-providers-vmware/issues/23
cc @tjyang

**Comment by carbonin** [comment]
I think the cloud-init payload for VMware images might be delivered through the floppy device, but I can't remember for sure ... @jvlcek @bdunne do either of you guys know?

**Comment by tjyang** [comment]
Hi All.
Just an FYI. See https://www.centos.org/forums/viewtopic.php?t=47519

**Comment by jvlcek** [comment]
cloud-init, at one point a while ago, did use the floppy device to deliver the user data payload but that was supposed to be discontinued. I'm not fully sure what the current state is but I'd be surprised if cloud-init still required a floppy to do user data payload injection.

**Comment by bdunne** [comment]
I think it was used on RHEV as well, not sure if that is still the case.  cc @jhernand

**Comment by mfeifer** [comment]
@simaishi can you look at this one? (jason says)

**Comment by simaishi** [comment]
Yes, I'm checking (also a few other issues in this repo)...

**Comment by simaishi** [comment]
CentOS 8 does not support floppy drive, this is no longer an issue in Jansa and forward.
