### ISSUE TITLE
4.5G root partition too small for vmware appliance

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-appliance-build#219]
Hi 

* This current miq instance with master branch without upgrade on miq01 machine.
```
[root@miq01 ~]# df -lh
Filesystem                              Size  Used Avail Use% Mounted on
/dev/mapper/vg_system-lv_os             4.5G  3.8G  718M  85% /
<snipped>

[root@miq01 ~]# ls /opt/
manageiq  rh  rubies
[root@miq01 ~]#

```
* On another instance miq02, I  am out of root diskspace easily by  upgrade command.
```
vmdb && systemctl  stop evmserverd && git pull && bin/update && reboot
```
*  Please increase / size, if I am not doing anything wrong.

**Comment by tjyang** [comment]
Hi @simaishi ,

Can the disk layout  have  extra 10-20G  unassigned space  ?
So one can assign the free space to vg_system or vg_data volume groups when needed.

```
[root@miq01 log]# pvs
  PV         VG        Fmt  Attr PSize  PFree
  /dev/sda2  vg_system lvm2 a--  26.00g 140.00m
  /dev/sda5  vg_data   lvm2 a--  13.50g  20.00m

[root@miq01 ~]# lvs
  LV               VG        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_pg            vg_data   -wi-ao----  13.48g                                 
  lv_home          vg_system -wi-ao----   1.00g                                 
  lv_os            vg_system -wi-ao----   4.50g                                 
  lv_swap          vg_system -wi-ao----   5.86g                                 
  lv_tmp           vg_system -wi-ao----   1.00g                                 
  lv_var           vg_system -wi-ao----   2.00g                                 
  lv_var_log       vg_system -wi-ao----  11.00g                                 
  lv_var_log_audit vg_system -wi-ao---- 512.00m                                 
[root@miq01 ~]#

```

**Comment by simaishi** [comment]
@tjyang We actually have a need to increase /var size as well, so let me talk to a few people and figure out what we need to do. I like your idea of leaving some 'open' space 😄

**Comment by tjyang** [comment]
@simaishi, we have this practice at work of leaving open space, so admin can extend and resize lv on the fly.  I can easily add /dev/sdb vmdk file but that will make this appliance with two vmdk files  hard/impossible to do v2v(VMware to OpenStack) later.
