### ISSUE TITLE
Appliance Properties shows "Red Hat Enterprise Linux 6 64 bit"

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-appliance-build#26]
Downloading/Importing CentOS 7.1 built appliance ova to Fusion, the General properties of an appliance shows "Red Hat Enterprise Linux 6 64-bit" should be the "... 7 64-bit" string.  not sure where the property comes from, not in our config files, could be set in Imagefactory/Oz land.

**Comment by JPrause** [comment]
Spoke with Alberto and the issue as described still exists.

**Comment by Fryguy** [comment]
@simaishi Bump 🐢   This issue as opened in a slightly different way in ManageIQ/manageiq-appliance#121

**Comment by simaishi** [comment]
ImageFactory doesn't expose the OS setting and it's hard-coded as "rhel6_64Guest".

https://github.com/redhat-imaging/imagefactory/blob/master/imagefactory_plugins/ovfcommon/ovfcommon.py#L465-L469

The only way to 'fix' this currently is to overwrite the value in Imagefactory source that's on our build machine...

**Comment by simaishi** [comment]
I see an open issue in imagefactory: https://github.com/redhat-imaging/imagefactory/issues/401
