### ISSUE TITLE
libsemanage could not query record value (No such file or directory) in appliance build log

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-appliance-build#27]
In ~/anaconda-post.log:

```
I, [2015-08-20T20:27:52.311137 #605]  INFO -- : Writing /var/www/miq/vmdb/public/assets/patternfly/spinner-sm-f9033f86537f6271dd74eac8e25841fb8fcdfc8b9f2efc7affa7f520b9270ffc.gif
I, [2015-08-20T20:27:52.314773 #605]  INFO -- : Writing /var/www/miq/vmdb/public/assets/patternfly/spinner-xs-e40eaf96c7c329bd6068a579875838af341473876b8ef9c2f1fa337af209f167.gif
I, [2015-08-20T20:27:52.318372 #605]  INFO -- : Writing /var/www/miq/vmdb/public/assets/patternfly/spinner-e7faaa2d32659bae5d6613d5ea94ce9eb15b9075791e7a845f90313f0806d2cc.gif
libsemanage.dbase_llist_query: could not query record value (No such file or directory).
+ sysctl -p /etc/sysctl.conf
+ rm -f /var/www/miq/vmdb/certs/v2_key
+ systemctl enable miqtop
```

The `sysctl -p /etc/sysctl.conf` is from [here](https://github.com/ManageIQ/manageiq-appliance-build/blob/efc1308255e3d7d2f7fde4b1b1a24ab090eb1afb/kickstarts/base.ks.erb#L308)

Meaning, the it's coming from one of the `semanage` lines from `cfme-setup.sh` [here](https://github.com/ManageIQ/manageiq-appliance/blob/06c498e7f890b29b91ac563888ce34ec9402b442/cfme-setup.sh#L24-L41) might be failing.

It's hard to tell if it's a timing issue, @abellotti found [this](https://bugzilla.redhat.com/show_bug.cgi?id=434701) or a bug in our cfme-setup.sh code.

**Comment by JPrause** [comment]
Checking on issues with no recent updates.
Just reviewed last night's darga-nightly build,..this issue still exists as described.

**Comment by mfeifer** [comment]
@jrafanie is this still an issue?

**Comment by jrafanie** [comment]
No.  This is so old that most of the se linux things we were doing are now completely changed. Thanks!
