### ISSUE TITLE
OVA import: Unable to retrieve manifest or certificate file

### ISSUE THREAD

**Issue by kuklis** [ManageIQ/manageiq-appliance-build#285]
I'm getting "Unable to retrieve manifest or certificate file." error message when trying to import Gapri-5 OVA into vSphere 6.7.0

Workaround was to repackage the ova file with OVFtool:

ovftool --skipManifestCheck manageiq-vsphere-gaprindashvili-5.ova miq-gapri5.ova

**Comment by simaishi** [comment]
@kuklis I'm sorry for the delay getting back to you on this. I tried `gaprindashvili-5` as well as `ivanchuk-1` in vCenter 6.7.0 (with ESXi 6.7.0) environment and had no problem importing the images.

If you're still seeing the issue, please reopen with more info (exact vSphere version, etc.).
