### ISSUE TITLE
Build and push container images as a part of nightlies

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-appliance-build#373]
As long as we get the build machine set up with credentials to docker hub this should just be:

```bash
git clone https://github.com/ManageIQ/manageiq-pods
cd manageiq-pods
bin/build -d images -npr manageiq
```

**Comment by simaishi** [comment]
This is on my list, but I need to add support for using RH npm registry to podified build first...

**Comment by carbonin** [comment]
:+1: Just wanted to get it out there somewhere since I was trying to use the images today and they hadn't been pushed since before the kubernetes compatibility change.

**Comment by Fryguy** [comment]
We'll also need some basic deployment documentation for the website, because it should ultimately appear on manageiq.org.downloads

**Comment by simaishi** [comment]
yeah... there is an open issue: https://github.com/ManageIQ/manageiq.org/issues/620
