### ISSUE TITLE
[Appliance] Add Kafka service - Kasparov

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-appliance-build#374]
This should be similar to how we supply PostgreSQL out of the box on our appliance.  Basic Kafka with no HA or anything special.  If user wants an HA and/or a customized external Kafka. we should allow for that configuration as well.
- [X] Split out config file https://github.com/ManageIQ/manageiq/issues/20001
- [X] Create systemd units for kafka and zookeeper
- [X] Build an RPM
- [x] Add RPM to kasparov RPM repo https://github.com/ManageIQ/manageiq-rpm_build/pull/88
- [x] Configure SSL
- [x] Configure Authentication

Continues in https://github.com/ManageIQ/manageiq-appliance-build/issues/447

**Comment by chessbyte** [comment]
Split out Kafka configuration into https://github.com/ManageIQ/manageiq/issues/20001

**Comment by jvlcek** [comment]
@miq-bot assign @jvlcek

**Comment by jvlcek** [comment]
@Fryguy I am not able to edit this. I believe https://github.com/ManageIQ/manageiq-rpm_build/pull/88 is the PR for
 _Add kafka to the appliance build_ in the initial issue description.

@bdunne Please confirm.
@Fryguy Please add this PR to the initial description for  _Add kafka to the appliance build_

**Comment by bdunne** [comment]
Nope, https://github.com/ManageIQ/manageiq-rpm_build/pull/88 is for Add RPM to kasparov RPM repo which is checked off.  I changed _Add kafka to the appliance build_ to _Add kafka to the appliance as a RPM depedency_ to help clarify

**Comment by Fryguy** [comment]
Closing as this is in the Kasparov (and thus completed) column in the Roadmap
