### ISSUE TITLE
smem still needed?

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#378]
As per a quick discussion with @jrafanie, opening an issue to investigate if smem is sill needed on appliances.

smem was originally added in https://github.com/ManageIQ/manageiq-appliance-build/pull/84 for forked process, but the original reason no longer applies.

Came across this working on CentOS 8 based appliance, as the package doesn't exist (not even EPEL).

**Comment by Fryguy** [comment]
This was added for diagnostic purposes, to better be able to determine process memory on a running appliance, so it can probably be removed if it's not available.

**Comment by jrafanie** [comment]
Selfishly, I prefer the way smem presents PSS, USS, RSS vs. top only showing RSS but that's just me, I don't think it's required or documented.

**Comment by simaishi** [comment]
I have no problem building the RPM if it's useful.  If we're keeping it, we should probably document though 😄

**Comment by simaishi** [comment]
Built smem for CentOS 8, closing.
