### ISSUE TITLE
Vagrant kickstart partial not being trigger on manageiq-vagrant-master-20200211-4a069a15e6.box

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/manageiq-appliance-build#384]
This is a pretty specific case, since I haven't tested this else where, but when trying to use vagrant with vagrant+Virtualbox with this specific build:

http://releases.manageiq.org/manageiq-vagrant-master-20200211-4a069a15e6.box

I was unable ssh into the VM.

Upon closer inspection by logging in as root via the Virtualbox terminal, it seems like the `vagrant` user was not created, and the rest of the command for the partial have not been executed.

Haven't investigated further as to the extent of this issue, if it is specific to the build box for these images, or if recent changes in this repo might have caused this to happen and if it is affecting other builds as well.  I will be looking to it as time permits, but figured I would raise awareness that it was an issue for me at least.

Thanks,
-Nick

**Comment by NickLaMuro** [comment]
After investigating a bit more, it seems like it is related to the `pip install` step, and is similar to https://github.com/ManageIQ/manageiq-appliance-build/pull/382 (though a different error.

Comment in gitter a bit here:

https://gitter.im/ManageIQ/manageiq-appliance-build?at=5e4f2263dafa3029f642bc1d

I will try and get a stacktrace shortly...

**Comment by simaishi** [comment]
@NickLaMuro All builds were broken starting Feb 10 for master/ivanchuk. Depending on which version of virtualenv got picked up, you might see a different error. Please try with Feb 17 or later build.

**Comment by NickLaMuro** [comment]
@simaishi thanks.  Will do, and sorry for the noise.  It was probably a poor choice on my part to go with a nightly for my purposes, but will report back when I have tested with a newer version.

Thanks again!

**Comment by NickLaMuro** [comment]
Tested with the 20200218 and everything is installed for the build properly as suggested.

Thanks!   Closing.

**Comment by NickLaMuro** [comment]
Just wanted to leave a quick follow up:

If/when this does happen for anyone else, you can get around this and still get into the appliance by adding the following to the `Vagrantfile`:

```ruby
Vagrant.configure("2") do |config|
  # ...
  config.ssh.insert_key = false
  config.ssh.username   = "root"
  config.ssh.password   = "smartvm"
end
```

So this will allow you to get access to the `anaconda-post.log` and determine what might have gone wrong, or do any other VM actions via `vagrant ssh`.
