### ISSUE TITLE
- Is there any timeline for how quickly AppStream will build the latest rubies? I remember software collections being way behind.

### ISSUE THREAD

**Issue by ghost** [ManageIQ/manageiq-appliance-build#403]
- Is there any timeline for how quickly AppStream will build the latest rubies? I remember software collections being way behind.
- I know we have required a minimum patch version in the past due to bugs in lower patch versions.  Is there any way to specify that?
- Does AppStream work properly with `Bundle.with_clean_env`?

_Originally posted by @bdunne in https://github.com/ManageIQ/manageiq-appliance-build/issues/393#issuecomment-600245345_

**Comment by bdunne** [comment]
@Chelsbells1123 Did you intend to open this issue?

**Comment by simaishi** [comment]
Closing the issue since the user account has been deleted (as per 'ghost'...)
