### ISSUE TITLE
Switch to rpm based install for ManageIQ source code

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-appliance-build#411]
- [X] Create manageiq-rpm_build repo: https://github.com/ManageIQ/manageiq-rpm_build
- [x] Create a yum repo at rpm.manageiq.org for official builds (@bdunne)
- [x] Upload RPMs https://github.com/ManageIQ/manageiq-rpm_build/pull/48
- [x] Update RPM metadata on rpm.manageiq.org (@bdunne) https://github.com/ManageIQ/manageiq-rpm_build/pull/49
- [x] Update PRs to use the new rpm.manageiq.org yum repos
- [x] Update https://github.com/ManageIQ/manageiq-appliance-build/pull/417 to publish RPMs and update yum repo
- [x] manageiq-appliance-build with RPMs: https://github.com/ManageIQ/manageiq-appliance-build/pull/415
- [x] manageiq-pods with RPMs: https://github.com/ManageIQ/manageiq-pods/pull/485
- [x] nightly/release RPM build: https://github.com/ManageIQ/manageiq-appliance-build/pull/417
- [x] monolithic Docker image with RPMs: https://github.com/ManageIQ/manageiq/pull/20127 (depends on https://github.com/ManageIQ/manageiq-pods/pull/485)
- [x] source-based RPM builds for pods: https://github.com/ManageIQ/manageiq-pods/pull/491 (depends on  https://github.com/ManageIQ/manageiq-pods/pull/485)
- [x] manageiq-appliance with RPMs: https://github.com/ManageIQ/manageiq-appliance/pull/283
- [x] Remove temporary commit from manageiq-rpm_build: https://github.com/ManageIQ/manageiq-rpm_build/pull/46 (depends on https://github.com/ManageIQ/manageiq-appliance/pull/283)

---

We currently check out source code and run `bundle install` (and other needed rake tasks) during each appliance build. Switching to rpm based install will allo w us to run bundle/rake tasks only once per night, and build steps/times will be reduced for each appliance build.

This will also ensure appliance will have the exact same source code for the same night, which is not always the case for 'nightly' build right now, as `bundle install` can pick up a different plugin code.

The appliance update will be easier with RPM as well. However, if users want to update to a particular sha or at particular time, rpm will make it harder to accomplish that. I don't see that being a big issue though.

Steps will be:

In a container,
- Clone source code
- Run bundle/rake
- Create tarball(s)
- Build RPM(s)

Then, kick off appliance build.

"Building RPMs" step will need to allow customization. For us, I'm thinking we can initiate Copr RPM build from the container as we'll need to make sure users can access nightly RPMs. Then, we won't need to save any artifacts from the container.

**Comment by simaishi** [comment]
@Fryguy @chessbyte Is it correct to assume we will only support updates via rpm once this change is implemented?

@jrafanie Will there be any issue installing gems to non-default location by setting a path (just like how downstream works)?

Trying to think what should still work on the appliance once this change is implemented in regards to gem/bundle. If we're not expecting users to run `bundle update`, for example, there will be no reason for them to run `bundle clean` and that will make bundle clean issues being discussed in https://github.com/ManageIQ/manageiq-appliance-build/issues/408 as well as https://github.com/ManageIQ/manageiq-appliance-build/issues/393 a lot less relevant if not obsolete.

**Comment by Fryguy** [comment]
Yes, that sounds reasonable to me.  I think separately we should have instructions on how to convert an appliance to a git based one for dev purposes, but other than that, once we go rpm, that would be the one way.

**Comment by jrafanie** [comment]
> @jrafanie Will there be any issue installing gems to non-default location by setting a path (just like how downstream works)?

`--path`  is a default option supported by bundler so I think that should be fine.  I can't remember, is that how you intend to use it?

**Comment by Fryguy** [comment]
I think the biggest thing we have to make sure works properly, but is complicated, is the way automate uses gems (and allowing people to install gems without affecting the core).  This was a big issue downstream, but I'm not sure it's an issue upstream.

**Comment by simaishi** [comment]
Initially I'm following the downstream steps and setting GEM_HOME during bundle. BUNDLE_PATH -> GEM_PATH change was something we did for downstream when we went from bundler 1.15 to 1.16+.

Is it a requirement that our bundled gems and user installed gems go into different directory?  automate should be able to access all bundled gems (including git based) as well as user installed gems?

**Comment by Fryguy** [comment]
> automate should be able to access all bundled gems (including git based) as well as user installed gems?

I don't see why automate can't access bundled gems.  @jrafanie?

**Comment by Fryguy** [comment]
https://github.com/ManageIQ/manageiq-rpm_build

**Comment by jrafanie** [comment]
To be honest, I just don't remember how this was supposed to work for automate gems in older versions.  I believe there was some inconsistency with downstream with how gems were packaged and if their location was on the GEM_HOME or GEM_PATH earlier than the system gems.  I haven't had cycles to look at this though.

**Comment by Fryguy** [comment]
Done!
