### ISSUE TITLE
Include a dependency manifest in the build

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-appliance-build#429]
@simaishi As discussed, we already have the Ruby gems list, but it would be nice to have python, node, and even system packages in the manifest.

- [x] ruby gems (https://github.com/ManageIQ/manageiq-rpm_build/pull/64)
- [x] npm packages (https://github.com/ManageIQ/manageiq-rpm_build/pull/64)
- [x] webpack (https://github.com/ManageIQ/manageiq-rpm_build/pull/75)
- [x] python modules (https://github.com/ManageIQ/manageiq-rpm_build/pull/108)
- [x] rpm (https://github.com/ManageIQ/manageiq-appliance/pull/289, https://github.com/ManageIQ/manageiq-rpm_build/pull/73, #431 and https://github.com/ManageIQ/manageiq-pods/pull/563)

**Comment by Fryguy** [comment]
I'd like the manifest to have (if possible): package, version, license, source

where `source` is the source of the package.  In the case of system packages, source would be which yum repository it came from.  For something like Ruby, it might be things like rubygems.org vs rubygems.manageiq.org vs a git URL.  As this might be difficult to get, I'm ok with this being missing.

**Comment by Fryguy** [comment]
Sounds good to me @simaishi

**Comment by bdunne** [comment]
Anything else required before closing this issue?
