### ISSUE TITLE
Move from CentOS 8 to CentOS Stream

### ISSUE THREAD

**Issue by pemcg** [ManageIQ/manageiq-appliance-build#459]
Application images:

- [x] rpms
  - [x] [manageiq-ansible-venv](https://github.com/ManageIQ/manageiq-rpm_build/pull/167)
- [x] podified
  - [x] [manageiq-pods base image](https://github.com/ManageIQ/manageiq-pods/pull/725)
  - [x] [container-httpd](https://github.com/ManageIQ/container-httpd/pull/62)
  - [x] [container-httpd-init](https://github.com/ManageIQ/container-httpd-init/pull/14)
  - [x] ~container-memcached~ Not needed because it's pure ubi8
  - [x] [container-postgresql](https://github.com/ManageIQ/container-postgresql/pull/29)
- [x] [appliance](https://github.com/ManageIQ/manageiq-appliance-build/pull/481)

---

Non application images:

- [x] [RPM Builder](https://github.com/ManageIQ/manageiq-rpm_build/pull/154)
- [x] [miq-bot](https://github.com/ManageIQ/miq_bot/pull/564)
- [x] [manageiq_org-spaces_purger](https://github.com/ManageIQ/manageiq_org-spaces_purger/pull/2)

**Comment by Fryguy** [comment]
https://centos.org/distro-faq/#q7-how-do-i-migrate-my-centos-linux-8-installation-to-centos-stream

**Comment by Fryguy** [comment]
cc @simaishi

**Comment by bdunne** [comment]
Everything is checked off, closing
