### ISSUE TITLE
VMware Guest Customization does not work for OVA Image

### ISSUE THREAD

**Issue by ashkuren** [ManageIQ/manageiq-appliance-build#484]
As stated, by default OVA image is unable to use vmware customization specs.
Image: `kasparov-1`

VMware error:
```
Customization of the guest operating system 'centos64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.
```

The reason could be related to this error that shows on `dnf` command execution.
```
Modular dependency problems:

 Problem 1: conflicting requests
  - nothing provides module(perl:5.26) needed by module perl-IO-Socket-SSL:2.066:8030020201222215140:1e4bbb35-0.x86_64
 Problem 2: conflicting requests
  - nothing provides module(perl:5.26) needed by module perl-libwww-perl:6.34:8030020201223164340:b967a9a2-0.x86_64
```

**Comment by bdunne** [comment]
@ashkuren Do we need to have Vmware Tools installed for this feature to work?

**Comment by ashkuren** [comment]
[open-vm-tools](https://github.com/vmware/open-vm-tools) and its dependencies should be installed which is already the case. After some investigation, the symptoms are similar to this [post](https://communities.vmware.com/t5/VMware-vCenter-Discussions/VM-customization-does-not-work-until-booted-once/td-p/522372). `open-vm-tools` are not identified on the first boot, vm is not powered on and customizations fail.

After first boot/shutdown/convert to template the vm customizations are triggered but fail because of another issue with `cloud-init`. I think this should be a separate issue, but in order to workaround it, i have changed this parameter:
```bash
# Enable Vmware custom spec (Disable Cloudinit vmware custom spec)
sed -i '/^disable_vmware_customization/ s/false/true/' /etc/cloud/cloud.cfg
```
