### ISSUE TITLE
We need an upgrade path for appliances after #559 (qpid proton from epel)

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-appliance-build#560]
https://github.com/ManageIQ/manageiq-appliance-build/pull/559 changed the yum/dnf configuration and we should provide a way to upgrade appliances so as not to require a full appliance replacement for such a minor change.

We'll need to run `dnf config-manager --setopt=epel.exclude= --save` before we can upgrade rpms that depend on qpid-proton-c 0.37.0 as we previously excluded the epel version of qpid-proton that we now need.

**Comment by Fryguy** [comment]
Is this still a thing that's needed @jrafanie?

**Comment by jrafanie** [comment]
No, I think this is resolved by not supporting upgrades from el/ubi 8 to 9.
