### ISSUE TITLE
Version number sha is not helpful

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-appliance-build#57]
The version number in the UI currently reports `version.yyyymmddhhmmss_sha`.  The problem is that the short sha refers to the manageiq-appliance-build git sha, not the manageiq git sha from which the build was made.  Now that we are split into multiple repos, I wonder if it even makes sense to have the git sha in the version number.  I believe we agreed to bump the version number for every build, so there should be a corresponding git tag to go with that.  The only use case that I am unsure of is nightly builds.  I would assume that they are currently something like `master.date_sha`.  Although anyone reporting an issue on a nightly should be familiar enough with git to get the sha if needed.  I feel like we don't need it anymore and should drop the `_sha`.  Anyone disagree?

**Comment by Fryguy** [comment]
I like the SHA on the non-tag builds.  That way you know *exactly* which commit.  Date is not sufficient if you do 2 in a day, or master is a commit or two behind what you'd expect for that day.

**Comment by Fryguy** [comment]
For tag builds, yeah, a SHA is not necessary.

**Comment by JPrause** [comment]
@bdunne @Fryguy just checking on issues with no recent update,...was this something we still wanted to change?

Just checked the darga nightly build and the Version shows: darga-3.20160908115602_23fa871

**Comment by Fryguy** [comment]
¯\\\_(ツ)_/¯ I'm ok with leaving this open

**Comment by simaishi** [comment]
I think this is already fixed - it should be getting sha from manageiq repo.

**Comment by JPrause** [comment]
@bdunne based on Satoe's comment,..can you close this issue.
