### ISSUE TITLE
Upstream appliance no longer display the Appliance Console motd

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-appliance-build#62]
With /etc/motd moved to /etc/motd.manageiq in manageiq-appliance repo,  upstream builds  no longer display:

```
Welcome to the Appliance Console

For a menu, please type: appliance_console
```

manageiq-appliance-build need to copy /etc/motd.manageiq back to /etc/motd during kickstart

**Comment by gtanzillo** [comment]
@carbonin Can you please look into this when you get some time?

**Comment by kbrock** [comment]
Thanks again @carbonin and @abellotti for finding / fixing
