### ISSUE TITLE
Stable "release" builds should go to upstream_stable, not upstream

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-appliance-build#71]
Need to expose the ["directory"](https://github.com/ManageIQ/manageiq-appliance-build/blob/4ab7fea97a86ecfd84997ba4384c2c17d52fc8b4/scripts/vmbuild.rb#L89) as a CLI option:

Then, change the [release script](https://github.com/ManageIQ/manageiq-appliance-build/blob/4ab7fea97a86ecfd84997ba4384c2c17d52fc8b4/bin/release-build.sh#L13) to default to "upstream_stable"

**Comment by simaishi** [comment]
Fixed in #86
