### ISSUE TITLE
/etc/issue and /etc/issue.net no longer updated

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-appliance-build#73]
We no longer get the updated

```
Welcome to the ManageIQ Virtual Appliance

You can browse to http://x.x.x.x/ or http://fqdn

CentOS Linux 7 (Core)
Kernel 3.10.0-229.14.1.el7.x86_64 on an x86_64
localhost login:
```

This was done for us via /etc/NetworkManager/dispatched.d/99-fix-issue

**Comment by carbonin** [comment]
@abellotti can you just assign this to me?  I'm already looking into it.

**Comment by carbonin** [comment]
@miq-bot assign @carbonin

**Comment by abellotti** [comment]
Can't seem to assign it to you, somehow you're not in the pull down.

On Thu, Oct 29, 2015 at 2:04 PM, Nick Carboni <notifications@github.com>
wrote:

> @miq-bot <https://github.com/miq-bot> assign @carbonin
> <https://github.com/carbonin>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManageIQ/manageiq-appliance-build/issues/73#issuecomment-152268213>
> .
>



-- 
*Alberto Bellotti*
abellott@redhat.com

**Comment by kbrock** [comment]
don't care how this gets called.

nice thing about the network manager solution is this gets called when dhcp responds - not when the system boots up. (slightly different)

**Comment by carbonin** [comment]
The fix I'm working on would move the current functionality from there to `/usr/sbin/ifup-local` which gets called with an interface as the argument after the interface comes up.

I know we now run `ifdown/ifup` after changing network configuration so I think this will do the trick even if it isn't exactly the same.

**Comment by kbrock** [comment]
@carbonin thanks. :+1:
